Provide more context on mkdir failures (#28)
For example, instead of:

```
Error: Permission denied (os error 13)
```

one will get:

```
Error: Failed to create `/var/lib/taskchampion-sync-server`.

Caused by:
    Permission denied (os error 13)
```

after this patch is applied.